### ISSUE TITLE
ContentType missing in fasthttp example

### ISSUE THREAD

**Issue by arigon** [elastic/go-elasticsearch#114] opened 2019-12-05 12:40 UTC
```
res, err := es.Count(
		es.Count.WithIndex(idx),
		es.Count.WithDocumentType("event"),
		es.Count.WithIgnoreUnavailable(true),
	)
```
The third parameter will add _?ignore_unavailable=true_ to the request. The fasthttp example is not setting the Content-Type and fasthttp will assume _application/x-www-form-urlencoded_ and therefore not allowing query parameters:
> When Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?'): '/4dcd04c11d9148d2aa5ed100d38726f9/event/_count?ignore_unavailable=true'

Adding _dst.Header.SetContentType("application/json")_ to the copyRequest function will solve this problem.

**Comment by karmi** [comment] 2019-12-08 14:23
> The fasthttp example is not setting the Content-Type (...)

That is surprising, since the `copyRequest()` method copies also the headers, which should include the `Content-Type` header, when it's set.

https://github.com/elastic/go-elasticsearch/blob/d562df6cd230ff351819a129a1d836c719b01704/_examples/fasthttp/fasthttp.go#L55-L59

I've improved the test a little bit in d562df6c, and verified manually with something like `fmt.Printf("Content-Type: %s\n", dst.Header.Peek("Content-Type"))` inside the `copyRequest()` method.

It looks like `fasthttp` is a bit too eager, if it adds the `Content-Type` header here. I've tried your example with `es.Count()` and I'm not getting an error response. Can you share more info or more complete code?

**Comment by arigon** [comment] 2019-12-11 15:05
Sorry for the late response.
I am using the fasthttp package of your example and the go library in version v6.8.5

I added your given Printf to get the Content-Type in the copyRequest() and it is empty.
here is why:

if r.Body != nil {
		req.Header[headerContentType] = headerContentTypeJSON
	}
https://github.com/elastic/go-elasticsearch/blob/6.x/esapi/api.count.go#L178

The body is of course nil, that's why the Content-Type is not set.

**Comment by karmi** [comment] 2019-12-18 07:08
I'm still wondering how to reproduce the error you're seeing with missing URL parameters...

**Comment by arigon** [comment] 2019-12-18 19:19
Have you tried it including the parameter: _es.Count.WithIgnoreUnavailable(true)_? if you omit this, it won't fail.

Here is some example code:

```
package main

import (
	"encoding/json"
	"fmt"
	"issue-fasthttp/fasthttp"
	"log"

	"github.com/elastic/go-elasticsearch/v6"
)

var es *elasticsearch.Client

func init() {
	cfg := elasticsearch.Config{
		Transport: &fasthttp.Transport{},
	}
	var err error
	es, err = elasticsearch.NewClient(cfg)
	if err != nil {
		log.Fatal(err)
	}
}

func main() {
	result, err := doDocumentsCount("3b9fcfc36eb4455a9c8c9fe779c29cdb")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(result)
}

func doDocumentsCount(index string) (map[string]interface{}, error) {
	res, err := es.Count(
		es.Count.WithIndex(index),
		es.Count.WithDocumentType("event"),
		es.Count.WithIgnoreUnavailable(true),
	)

	if err != nil {
		return nil, err
	}
	defer res.Body.Close()

	var r map[string]interface{}
	if err := json.NewDecoder(res.Body).Decode(&r); err != nil {
		return nil, err
	}

	return r, nil
}
```

**Comment by karmi** [comment] 2019-12-20 08:45
Yes, I did run it with `es.Count.WithIgnoreUnavailable(true)`. 

I've added `fmt.Printf("> %s; %s\n", freq.URI(), freq.Header.Peek("Content-Type"))` to the RoundTrip method in the example, and I'm not seeing the Content-Type set:

```
> http://localhost:9200/_search?pretty=true; application/json
> http://localhost:9200/test/_count?ignore_unavailable=true; 
[200 OK] {"count":0,"_shards":{"total":0,"successful":0,"skipped":0,"failed":0}}
```

**Comment by karmi** [comment] 2020-01-08 09:48
Any news?

**Comment by arigon** [comment] 2020-01-08 12:07
I am using it with the workaround by manually setting the content-type. if you want, you can close it. but I think the content-type should be set without a body as well?

**Comment by karmi** [comment] 2020-01-08 12:12
So the mystery to me is that I can't replicate the error you've mentioned — in my case, fasthttp is not setting the `Content-Type` to `application/x-www-form-urlencoded`.

I don't think we should set the content type when there's no body being sent?

**Comment by arigon** [comment] 2020-01-08 12:32
According to the RFC 7231 it is optional for GET. fasthttp is not setting the content-type in my example, it is using it as fallback because no content-type is set (my assumption, haven't checked the fasthttp library regarding this).

**Comment by Anaethelion** [comment] 2023-10-19 15:06
Closing this as issue was not reproducible.

**Closed by Anaethelion** 2023-10-19 15:06 UTC
