### ISSUE TITLE
go build stuck at elasticsearch v8.7.1

### ISSUE THREAD

**Issue by mskKote** [elastic/go-elasticsearch#680] opened 2023-06-08 15:52 UTC
go build failed after 14 minutes of compiling elasticsearch package

[go build -x logs](https://gist.github.com/mskKote/4e41d3944ca4775a8588398c12ee04f9)

env
> Ubuntu 22.04.2 LTS
> 6gb OS / 25gb disk
> go version 1.20.5
> Docker version 24.0.2

**Comment by Anaethelion** [comment] 2023-06-09 16:32
Hi @mskKote 

I've had a look and I don't see anything unusual.
I've pulled locally the image `golang:1.20.5-alpine3.18`, made a test project with the client in `v8.7.1`, compiled the code and ran the test suite successfully.

Since I cannot reproduce based on the informations provided I'm going to close the issue for now.
If you have more I'd be happy to take a look!

**Closed by Anaethelion** 2023-06-09 16:32 UTC
