### ISSUE TITLE
some godoc links 404

### ISSUE THREAD

**Issue by jordansissel** [elastic/go-elasticsearch#74] opened 2019-07-30 16:56 UTC
![image](https://user-images.githubusercontent.com/131818/62149286-3b46e180-b2b0-11e9-87c2-02eb28d75125.png)

Page: https://godoc.org/github.com/elastic/go-elasticsearch#Client

The link for `esapi.API` points to https://godoc.org/github.com/elastic/go-elasticsearch/v8/esapi#API which 404's:

![image](https://user-images.githubusercontent.com/131818/62149321-4f8ade80-b2b0-11e9-831d-0cfa3eb79275.png)

**Comment by karmi** [comment] 2019-07-31 05:43
Heya, this one is probably hard to "fix" — the package uses the version suffix in import paths, in order to correctly work with Go modules (and to allow multiple clients with different versions in one project). It seems like Godoc has trouble dealing with that in the internal links — maybe it's worth opening an issue with Godoc?

**Comment by karmi** [comment] 2019-08-02 07:07
Hello, any news here?

**Comment by julieqiu** [comment] 2019-09-17 14:25
This will be fixed in the new Go discovery site. See https://github.com/golang/go/issues/33654 for details.

**Comment by karmi** [comment] 2019-11-06 16:40
Thanks for the link, @julieqiu! It looks like the issue is still not resolved, but unfortunately, there's not much the package can do at this point other than wait for it to be fixed on the godoc.org site...

**Closed by karmi** 2019-11-06 16:40 UTC

**Comment by jordansissel** [comment] 2019-11-13 23:30
i filed an issue upstream anyway with what I think is the right place - https://github.com/golang/gddo/issues/661

**Comment by jordansissel** [comment] 2019-11-13 23:32
Ahh, good timing re: @julieqiu's comment. The new docs site for go seems to work in this case:

https://pkg.go.dev/github.com/elastic/go-elasticsearch?tab=doc

an "esapi" link goes to https://pkg.go.dev/github.com/elastic/go-elasticsearch/esapi?tab=doc#API and works (no 404).

**Comment by karmi** [comment] 2019-11-14 09:20
Thanks, @jordansissel!
