### ISSUE TITLE
Data race in estransport.Perform

### ISSUE THREAD

**Issue by johanbrandhorst** [elastic/go-elasticsearch#147] opened 2020-04-29 13:32 UTC
Not entirely sure why this is happening, but I think it has something to do with the retrying mechanism. Here's the backtrace:
```
==================
WARNING: DATA RACE
Write at 0x00c00038e5a8 by main goroutine:
	github.com/elastic/go-elasticsearch/v7/estransport.(*Client).setReqURL()
		/<REDACTED>/github.com/elastic/go-elasticsearch/v7@v7.6.0/estransport/estransport.go:314 +0x128
	github.com/elastic/go-elasticsearch/v7/estransport.(*Client).Perform()
		/<REDACTED>/github.com/elastic/go-elasticsearch/v7@v7.6.0/estransport/estransport.go:220 +0x362
	github.com/elastic/go-elasticsearch/v7/esapi.PingRequest.Do()
		/<REDACTED>/github.com/elastic/go-elasticsearch/v7@v7.6.0/esapi/api.ping.go:107 +0x609
	github.com/elastic/go-elasticsearch/v7/esapi.newPingFunc.func1()
		/<REDACTED>/github.com/elastic/go-elasticsearch/v7@v7.6.0/esapi/api.ping.go:21 +0x1f8
	main.main()
		_testmain.go:44 +0x223

Previous read at 0x00c00038e5a8 by goroutine 45:
	net/http.(*Request).write()
		/usr/local/go/src/net/http/request.go:565 +0x15e3
	net/http.(*persistConn).writeLoop()
		/usr/local/go/src/net/http/transport.go:2280 +0x331

Goroutine 45 (running) created at:
	net/http.(*Transport).dialConn()
		/usr/local/go/src/net/http/transport.go:1648 +0xc33
	net/http.(*Transport).dialConnFor()
		/usr/local/go/src/net/http/transport.go:1365 +0x14f
==================
```

**Comment by karmi** [comment] 2020-04-29 14:42
The retry feature _should_ be definitely safe for concurrent use. Can you provide a little more info on how you're initializing the client and calling the Ping API?

**Comment by karmi** [comment] 2020-04-29 14:51
As a quick sanity check, I've added concurrent execution into this test:

https://github.com/elastic/go-elasticsearch/blob/e9eb76d55d12256a0777ad825bf25cd5e02fa105/estransport/estransport_integration_test.go#L49-L70

but I haven't seen a data race. I'll try some ad-hoc tests once I have more details about your setup.

**Comment by johanbrandhorst** [comment] 2020-04-29 14:54
Hey, thanks for the quick response! The case where I'm seeing this is as simple as this:
```go
cli, err := elasticsearch.NewClient(
	elasticsearch.Config{
		Addresses: []string{"http://" + address},
		// Race condition in retry logic:
		// https://github.com/elastic/go-elasticsearch/issues/147
		DisableRetry: true,
	},
)
if err != nil {
	return err
}

resp, err := cli.API.Ping()
if err != nil {
	return err
}
_ = resp.Body.Close()

if resp.IsError() {
	return fmt.Errorf("error pinging ElasticSearch")
}

return nil
```
In a loop waiting for the elastic search container to start. It doesn't always happen, but it has happened twice in the last week. I added the `resp.Body.Close` after the first time because I thought it might be something about reusing connections but it happened again with it.

**Comment by johanbrandhorst** [comment] 2020-04-29 14:59
The most representative test case would probably be to run this against a port that isn't serving anything (so responds with a `connection refused` or something like that). The error in the case where I discovered the data race is `http: server closed idle connection`.

**Comment by karmi** [comment] 2020-04-29 15:00
Hmm, this is even more mysterious, since you're not executing the API concurrently... Is it really the case? Is it really just a plain loop? Can you also try with `DisableRetry: true`, to see if it behaves differently?

-----

The closing of the body is indeed essential for keep-alive, and for the 100% correct operation, the body should be consumed as well — but in case of the Ping API, there shouldn't be any body (it's a `HEAD` request).

**Comment by johanbrandhorst** [comment] 2020-04-29 15:05
> Hmm, this is even more mysterious, since you're not executing the API concurrently... Is it really the case? Is it really just a plain loop? Can you also try with `DisableRetry: true`, to see if it behaves differently?

It really is a simple loop, no concurrent use of the client, new client every time. It's why I'm confused too :joy:. I will disable retries now and let you know if I see it again, but because it reproduces rarely I can't know for sure.

**Comment by karmi** [comment] 2020-04-29 15:06
So I have tried now this isolated script, and it doesn't trigger any race condition:

```golang
//+build ignore

package main

import (
	"log"
	"os"

	"github.com/elastic/go-elasticsearch/v8"
	"github.com/elastic/go-elasticsearch/v8/estransport"
)

func main() {
	log.SetFlags(0)

	cfg := elasticsearch.Config{
		Addresses: []string{
			"http://localhost:1000",
			// "http://localhost:1001",
			// "http://localhost:1002",
		},

		Logger: &estransport.ColorLogger{Output: os.Stdout},

		EnableDebugLogger: true,
	}

	es, err := elasticsearch.NewClient(cfg)
	if err != nil {
		log.Fatalf("Error creating the client: %s", err)
	}
	log.Println("Client ready with URLs:", es.Transport.(*estransport.Client).URLs())

	res, err := es.Ping()
	if err != nil {
		log.Fatalf("Error getting response: %s", err)
	}
	log.Println(res)
}
```

Output:

```
go run -race tmp/test-retries-race.go 
Client ready with URLs: [http://localhost:1000]
  HEAD http://localhost:1000/ ERROR 3ms
» ERROR dial tcp [::1]:1000: connect: connection refused
  HEAD http://localhost:1000/ ERROR 1ms
» ERROR dial tcp [::1]:1000: connect: connection refused
  HEAD http://localhost:1000/ ERROR 1ms
» ERROR dial tcp [::1]:1000: connect: connection refused
Error getting response: dial tcp [::1]:1000: connect: connection refused
exit status 1
```

**Comment by johanbrandhorst** [comment] 2020-04-29 15:08
I think the issue is mutating the `*http.Request` after passing it to the `Transport`. Just judging by the trace it looks like the Go HTTP stack is continuously reading from it in the background.

**Comment by karmi** [comment] 2020-04-29 15:09
Same story when I add a little goroutine around it:

```golang
//+build ignore

package main

import (
	"log"
	"os"
	"sync"

	"github.com/elastic/go-elasticsearch/v8"
	"github.com/elastic/go-elasticsearch/v8/estransport"
)

func main() {
	log.SetFlags(0)

	var wg sync.WaitGroup

	cfg := elasticsearch.Config{
		Addresses: []string{
			"http://localhost:1000",
			// "http://localhost:1001",
			// "http://localhost:1002",
		},

		Logger: &estransport.ColorLogger{Output: os.Stdout},

		EnableDebugLogger: true,
	}

	es, err := elasticsearch.NewClient(cfg)
	if err != nil {
		log.Fatalf("Error creating the client: %s", err)
	}
	log.Println("Client ready with URLs:", es.Transport.(*estransport.Client).URLs())

	for i := 1; i <= 5; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			res, err := es.Ping()
			if err != nil {
				log.Fatalf("Error getting response: %s", err)
			}
			log.Println(res)
		}()
	}

	wg.Wait()
}
```

Output:

```
go run -race tmp/test-retries-race.go 
Client ready with URLs: [http://localhost:1000]
  HEAD http://localhost:1000/ ERROR 5ms
» ERROR dial tcp [::1]:1000: connect: connection refused
  HEAD http://localhost:1000/ ERROR 6ms
» ERROR dial tcp [::1]:1000: connect: connection refused
  HEAD http://localhost:1000/ ERROR 6ms
» ERROR dial tcp [::1]:1000: connect: connection refused
  HEAD http://localhost:1000/ ERROR 8ms
» ERROR dial tcp [::1]:1000: connect: connection refused
  HEAD http://localhost:1000/ ERROR 8ms
» ERROR dial tcp [::1]:1000: connect: connection refused
  HEAD http://localhost:1000/ ERROR 3ms
» ERROR dial tcp [::1]:1000: connect: connection refused
  HEAD http://localhost:1000/ ERROR 6ms
» ERROR dial tcp [::1]:1000: connect: connection refused
  HEAD http://localhost:1000/ ERROR 4ms
» ERROR dial tcp [::1]:1000: connect: connection refused
  HEAD http://localhost:1000/ ERROR 3ms
» ERROR dial tcp [::1]:1000: connect: connection refused
Error getting response: dial tcp [::1]:1000: connect: connection refused
exit status 1
```

**Comment by johanbrandhorst** [comment] 2020-04-29 15:10
This is using `v7` of the API if it makes any difference.

**Comment by karmi** [comment] 2020-04-29 15:11
> I think the issue is mutating the *http.Request after passing it to the Transport.

That would indeed trigger a race condition, but the strange thing is that it's hard to replicate...

I'll try the same with the `7.6` branch.

**Comment by karmi** [comment] 2020-04-29 15:13
No success with `7.6`. I know I did a _lot_ of testing for the retry feature during development, so it would be pretty strange if it would manifest even in a simple case like this...

I can try reading through the code later, if I see something suspicious, but without a replication, it's usually pretty hard to detect the bug.

**Comment by johanbrandhorst** [comment] 2020-04-29 15:20
Managed to reproduce it with a slight modification of your code:

1. Start elasticsearch 7.6.2 locally
   ```shell
   $ docker run --rm -d --name elasticsearch -p 9200:9200 elasticsearch:7.6.2
   ```
1. Immediately afterwards, run the test:
```go
package main_test

import (
	"log"
	"os"
	"sync"
	"testing"

	elasticsearch "github.com/elastic/go-elasticsearch/v7"
	"github.com/elastic/go-elasticsearch/v7/estransport"
)

func TestWhatever(t *testing.T) {
	log.SetFlags(0)

	var wg sync.WaitGroup

	cfg := elasticsearch.Config{
		Addresses: []string{
			"http://localhost:9201",
			// "http://localhost:1001",
			// "http://localhost:1002",
		},

		Logger: &estransport.ColorLogger{Output: os.Stdout},

		EnableDebugLogger: true,
	}

	es, err := elasticsearch.NewClient(cfg)
	if err != nil {
		log.Fatalf("Error creating the client: %s", err)
	}
	log.Println("Client ready with URLs:", es.Transport.(*estransport.Client).URLs())

	for i := 1; i <= 5; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			res, err := es.Ping()
			if err != nil {
				log.Fatalf("Error getting response: %s", err)
			}
			log.Println(res)
		}()
	}

	wg.Wait()
}
```

Traceback:
```
$ go test -race ./...
Client ready with URLs: [http://localhost:9200]
  HEAD http://localhost:9200/ ERROR 7ms
» ERROR EOF
  HEAD http://localhost:9200/ ERROR 8ms
» ERROR http: server closed idle connection
==================
WARNING: DATA RACE
Write at 0x00c00029a028 by goroutine 11:
  github.com/elastic/go-elasticsearch/v7/estransport.(*Client).setReqURL()
      /<REDACTED>/github.com/elastic/go-elasticsearch/v7@v7.6.0/estransport/estransport.go:314 +0x128
  github.com/elastic/go-elasticsearch/v7/estransport.(*Client).Perform()
      /<REDACTED>/github.com/elastic/go-elasticsearch/v7@v7.6.0/estransport/estransport.go:220 +0x362
  github.com/elastic/go-elasticsearch/v7/esapi.PingRequest.Do()
      /<REDACTED>/github.com/elastic/go-elasticsearch/v7@v7.6.0/esapi/api.ping.go:107 +0x609
  github.com/elastic/go-elasticsearch/v7/esapi.newPingFunc.func1()
      /<REDACTED>/github.com/elastic/go-elasticsearch/v7@v7.6.0/esapi/api.ping.go:21 +0x1f8
Error getting response: http: server closed idle connection
  /<REDACTED>/cmd_test.TestWhatever.func1()
      /<REDACTED>/main_test.go:40 +0xd5

Previous read at 0x00c00029a028 by goroutine 33:
  net/http.(*Request).write()
      /usr/lib/go/src/net/http/request.go:565 +0x15e3
  net/http.(*persistConn).writeLoop()
      /usr/lib/go/src/net/http/transport.go:2280 +0x331

Goroutine 11 (running) created at:
  /<REDACTED>/cmd_test.TestWhatever()
      /<REDACTED>/main_test.go:38 +0x441
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:991 +0x1eb

Goroutine 33 (finished) created at:
  net/http.(*Transport).dialConn()
      /usr/lib/go/src/net/http/transport.go:1648 +0xc33
  net/http.(*Transport).dialConnFor()
      /usr/lib/go/src/net/http/transport.go:1365 +0x14f
FAIL    /<REDACTED>/cmd    0.025s
FAIL
```

**Comment by johanbrandhorst** [comment] 2020-04-29 15:21
You may have to keep running the test if it passes at first. It will only work while the elasticsearch container is starting up (takes about 22 seconds on my machine)

**Comment by karmi** [comment] 2020-04-29 15:24
I'll have a look into it. You're starting Elasticsearch with `9200` published, but configuring the client to use `9201`, is that correct?

**Comment by johanbrandhorst** [comment] 2020-04-29 15:30
Sorry, that's a typo, I was using 9201 because 9200 was in use, but it should be the same port, of course.

**Comment by karmi** [comment] 2020-04-29 15:58
Can you try the same on your side but with the `master` branch? Elasticsearch version isn't perhaps that important, but try with `8.0.0-SNAPSHOT`.

What I'm doing is first launching this script:

```
for i in {1..1000}; do go run -race tmp/test-retries-race.go; done;
```

And then running `make cluster` in the repository, which launches the `docker.elastic.co/elasticsearch/elasticsearch-oss:8.0.0-SNAPSHOT` image.

If you wouldn't replicate it with `v8`/`master`, then I can start looking at the differences between the branches.

**Comment by johanbrandhorst** [comment] 2020-04-29 16:06
You can't reproduce it by following my steps? It happened on the 3rd try for me. I will try against master, sure.

**Comment by johanbrandhorst** [comment] 2020-04-29 16:09
Reproduced on my second try on master:
```
$ go test -race .
Client ready with URLs: [http://localhost:9200]
  HEAD http://localhost:9200/ ERROR 5ms
» ERROR EOF
==================
WARNING: DATA RACE
Read at 0x00c00010a328 by goroutine 27:
  net/http.(*Request).write()
      /usr/lib/go/src/net/http/request.go:565 +0x15e3
  net/http.(*persistConn).writeLoop()
      /usr/lib/go/src/net/http/transport.go:2280 +0x331

Previous write at 0x00c00010a328 by goroutine 10:
  github.com/elastic/go-elasticsearch/v8/estransport.(*Client).setReqURL()
      /home/johan/go/pkg/mod/github.com/elastic/go-elasticsearch/v8@v8.0.0-20200429055951-e9eb76d55d12/estransport/estransport.go:339 +0x128
  github.com/elastic/go-elasticsearch/v8/estransport.(*Client).Perform()
      /home/johan/go/pkg/mod/github.com/elastic/go-elasticsearch/v8@v8.0.0-20200429055951-e9eb76d55d12/estransport/estransport.go:245 +0x380
  github.com/elastic/go-elasticsearch/v8/esapi.PingRequest.Do()
      /home/johan/go/pkg/mod/github.com/elastic/go-elasticsearch/v8@v8.0.0-20200429055951-e9eb76d55d12/esapi/api.ping.go:107 +0x609
  github.com/elastic/go-elasticsearch/v8/esapi.newPingFunc.func1()
      /home/johan/go/pkg/mod/github.com/elastic/go-elasticsearch/v8@v8.0.0-20200429055951-e9eb76d55d12/esapi/api.ping.go:21 +0x1f8
  <REDACTED>/cmd_test.TestWhatever.func1()
      /<REDACTED>/cmd/main_test.go:40 +0xd5

Goroutine 27 (running) created at:
  net/http.(*Transport).dialConn()
      /usr/lib/go/src/net/http/transport.go:1648 +0xc33
  net/http.(*Transport).dialConnFor()
      /usr/lib/go/src/net/http/transport.go:1365 +0x14f

Goroutine 10 (running) created at:
  <REDACTED>/cmd_test.TestWhatever()
      /<REDACTED>/cmd/main_test.go:38 +0x441
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:991 +0x1eb
==================
  HEAD http://localhost:9200/ ERROR 5ms
» ERROR http: server closed idle connection
Error getting response: http: server closed idle connection
```

**Comment by karmi** [comment] 2020-04-30 06:26
Yes, unfortunately, I can't replicate it, neither with `master` nor with `7.6`, no matter how many runs I do... Which version of Go are you using? I'm using `go1.14 darwin/amd64`.

**Comment by johanbrandhorst** [comment] 2020-04-30 08:30
```shell
$ go version
go version go1.14.2 linux/amd64
```
That's weird. I'd be happy to test any patches if you want because it's easy for me to reproduce. It's a bit harder to isolate since it requires a starting elasticsearch container. I don't know exactly what the http response is of the starting server but I could not reproduce it without the container.

The good news is that I was able to reproduce it even with `DisableRetry: true`. So the problem is somewhere else, not the retrying logic.

**Comment by pengux** [comment] 2020-08-05 22:24
Can confirm this problem as I also encounter it. From the error, it seems like the request was sent in a new goroutine but then the Elasticsearch client trying to modify the same request at `setReqURL`

**Comment by pengux** [comment] 2020-08-06 12:26
Seems like the trick to replicate this issue is to `Immediately afterwards, run the test:`, which is to run the test when the docker container is still starting up, and `Error getting response: http: server closed idle connection` are returned. The data race is occurring on the next iteration of the retry loop (even though `DisableRetry` is set to `true`), when it tries to set the URL of the request. This is because the http.Transport is reading from the same field when it tries to write to persistent connection in a different goroutine. I could replicate this consistently by running:

```
docker stop elasticsearch && docker start elasticsearch && for i in {1..50}; do go test -v -race -cover -count=1 -coverprofile=tmp/integration-client.cov -tags='integration' -timeout=1h . -run "DataRace"; done
```

And the `DataRace` test function is:

```
func TestDataRaceForRequests(t *testing.T) {                         
    t.Run("DataRace", func(t *testing.T) {                       
        var wg sync.WaitGroup                                    
                                                                 
        es, err := elasticsearch.NewClient(elasticsearch.Config{ 
            DisableRetry: true,                                  
        })                                                       
        if err != nil {                                          
            log.Fatalf("Error creating the client: %s\n", err)   
        }                                                        
                                                                 
        for i := 1; i <= 5; i++ {                                
            wg.Add(1)                                            
            go func() {                                          
                defer wg.Done()                                  
                res, err := es.Ping()                            
                if err != nil {                                  
                    log.Printf("Error getting response: %s", err)
                }                                                
                t.Log(res)                                       
            }()                                                  
        }                                                        
                                                                 
        wg.Wait()                                                
    })                                                           
}
```

A solution would be to clone the request on a retry and the data race seems to be resolved after I tried that. I'll submit a PR for this.

**Comment by karmi** [comment] 2020-08-08 07:30
Thanks for the reproduction and the patch, @pengux! I've left couple of comments on the pull request,

**Comment by Anaethelion** [comment] 2023-10-19 15:21
Closing following the affiliated #178

**Closed by Anaethelion** 2023-10-19 15:21 UTC
